# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-08 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('run', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vivienda', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Region'),
        ),
        migrations.AddField(
            model_name='persona',
            name='Vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Vivienda'),
        ),
    ]
