# Generated by Django 2.1.3 on 2018-11-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('run', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('region', models.TextField()),
                ('ciudad', models.TextField()),
                ('tipo_vivienda', models.TextField()),
            ],
        ),
    ]
