# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-08 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=10)),
                ('raza', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
    ]
